name: Generate docs

on:
  workflow_call:
    secrets:
      github-token:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - id: previous-commit
        run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Helm Docs
        uses: gabe565/setup-helm-docs-action@531285940659679b5e1c3a41aa0c89d080f5f6b4

      - run: helm-docs

      - name: Commit release version
        id: latest-commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "['README.md']"
          author_name: GitHub
          author_email: noreply@github.com
          message: "doc(helm): re-generate documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      # copy commit status from latest
      - env:
          PREVIOUS_COMMIT: ${{ steps.previous-commit.outputs.commit_sha }}
          LATEST_COMMIT: ${{ steps.latest-commit.outputs.commit_sha }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          check_runs=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$REPO/commits/$PREVIOUS_COMMIT/check-runs | jq -r '.check_runs[] | [.name, .conclusion, .details_url] | @csv')

          IFS=$'\n'; for line in $check_runs; do
            IFS=',' read name conclusion detailsUrl <<< "${line}"
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO/check-runs \
              -d '{"name":'$name',"head_sha":"'$LATEST_COMMIT'","conclusion":'$conclusion',"details_url":'$detailsUrl'}'
          done
