name: Lint

on:
  workflow_call:
    inputs:
      required-dirs:
        description: 'List of space separated dirs to create before running the linter'
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Create required dirs
        if: ${{ inputs.required-dirs }}
        run: |
          mkdir -p ${{ inputs.required-dirs }}
          ls -lsa ${{ inputs.required-dirs }}

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH_EXEC: true
          VALIDATE_BASH: true
          VALIDATE_ENV: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
