name: "Terraform Validate"

on:
  workflow_call:

jobs:
  validate:
    runs-on: [ self-hosted, "staging" ]
    steps:
      - uses: actions/checkout@v3

      - name: Formatting check
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform validation
        run: terraform validate
